### ISSUE TITLE
Recruit crew

### ISSUE THREAD

**Issue by JonTheNiceGuy** [oggcamp/OggCamp-Activities#5]

**Comment by JonTheNiceGuy** [comment]
Need to follow up with Tobi to find out if the uni are still keen to be involved in crewing

**Comment by JonTheNiceGuy** [comment]
Define tasks for Crew - Probably:
* AV crew per room & Timings... :)
* Running Sign-in desk
* Running Merch Stand
* Supporting the Schedule & Updating online schedule

Ensure there's Rotation of Duties. Ensure we get some prior crew to help out as well.

Do we need First Aid support?

**Comment by lesp** [comment]
Jon, this looks like a good start.
Crew are needed for all of these points, it is important to buddy / rotate the crew so that they are not bored, and so they can see any talks etc.
First Aid Support is nice to have, but the venue should have first aiders / a process in place to contact should you need. Have you got a liaison on site that will be there all weekend? If so read them into what you are doing and make sure that they are contactable (radio / phone).
We had 3 people on the crew who were Dr's (Medical) and they provided first aid care.

Crew will also be needed for general fetching/carrying and point of contact for anyone lost in the building.

Hope that helps :)

**Comment by JonTheNiceGuy** [comment]
Thanks @lesp!
